name: CI - Build Docker Image and Update Manifest

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_update:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout App Repo
        uses: actions/checkout@v4

      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      
      - name: Build and push Docker image
        id: build-docker
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:${{ github.sha }}

      
      
      - name: Checkout Manifest Repo
        uses: actions/checkout@v4
        with:
          repository: gianpedrobc/Projeto_CD 
          token: ${{ secrets.PAT_TOKEN }}
          path: projeto-cd 

      
      
      - name: Update image tag in deployment.yaml
        run: |
          sed -i "s|image: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:${{ github.sha }}|" projeto-cd/k8s/Deployment.yaml

      
      
      - name: Commit and push changes
        run: |
          cd projeto-cd 
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          
          if ! git diff --quiet; then
            echo "Mudanças detectadas. Commitando e fazendo push..."
            git add k8s/Deployment.yaml
            git commit -m "ci: Atualiza imagem para ${{ github.sha }}"
            git push
          else
            echo "Nenhuma mudança na imagem para commitar."
          fi

